[package]
name = "complex-simd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd-math = { git = "https://github.com/MarcusTL12/simd-math-rs" }
